extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'

parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
  sourceType:  module

env:
  node: true
  es6:  true

globals:
  __PREFIX_LINKS__: true
  document: true
  fetch: true

settings:
  react:
    version: 16.2.0

rules:
  indent: [2, 4, { SwitchCase: 1 }]
  no-console: [0]
  func-names: [0]
  semi: [2, never]
  no-extra-semi: [2]
  space-before-function-paren:
    - 2
    - anonymous: never
      named:     never
  no-else-return: [0]
  space-infix-ops: [0]
  react/prefer-es6-class: [0]
  react/prefer-stateless-function: [0]
  react/jsx-filename-extension: [1, { extensions: ['.js', '.jsx'] }]
  react/prop-types: [0]
  import/no-unresolved: [0]
  global-require: [0]
