/**
 * This file defines a set of rules which can be applied
 * in order to standardize tool names, it's mostly involved
 * to extract things from the "other tools" questions.
 */

module.exports = [
    [/preact/i, 'Preact'],
    [/elm/i, 'elm'],
    [/cycle/i, 'Cycle.js'],
    [/knockout/i, 'Knockout'],
    [/jquery/i, 'jQuery'],
    [/mithril/i, 'Mithril'],
    [/inferno/i, 'Inferno'],
    [/(meteor|blaze)/i, 'Meteor'],
    [/riot/i, 'Riot'],
    [/ext/i, 'ext.js'],
    [/svelte/i, 'Svelte'],
    [/om/i, 'om'],
    [/choo/i, 'Choo'],
    [/hyperapp/i, 'hyperapp'],
    [/dojo/i, 'dojo'],
    [/reason/i, 'Reason'],
    [/alkali/i, 'alkali'],
    [/marionette/i, 'marionette'],
    [/stylus/i, 'Stylus'],
    [/kendo/i, 'Kendo'],
    [/marko/i, 'marko'],
    [/reagent/i, 'reagent'],
    [/haxe/i, 'haxe'],
    [/ampersand/i, 'ampersand'],
    [/rxjs/i, 'RxJS'],
    [/canjs/i, 'canjs'],
    [/prototype/i, 'prototype'],
    [/mootools/i, 'mootools'],
    [/glimmer/i, 'glimmer'],
    [/durandal/i, 'durandal'],
    [/moon/i, 'moon'],
    [/batman/i, 'batman'],
    [/flight/i, 'flight'],
    [/scala/i, 'scala'],
    [/webix/i, 'webix'],
    [/enyo/i, 'enyo'],
    [/quasar/i, 'quasar'],
    [/vanilla/i, 'vanilla javascript'],
    [/d3/i, 'd3'],
    [/three/i, 'ThreeJS'],
    [/cerebral/i, 'cerebral'],
    [/feathers/i, 'feathers'],
    [/angular/i, 'Angular'],
    [/underscore/i, 'underscore'],
    [/bootstrap/i, 'Bootstrap'],
    [/vuex/i, 'VueX'],
    [/flux/i, 'Flux'],
    [/pouch/i, 'PouchDB'],
    [/ngrx/i, 'NgRx'],
    [/graph\.?cool/i, 'graph.cool'],
    [/rxjs/i, 'RxJS'],
    [/parse/i, 'Parse'],
    [/meteor/i, 'Meteor'],
    [/realm/i, 'realm'],
    [/gun/i, 'Gun.js'],
    [/cycle/i, 'Cycle.js'],
    [/couchbase/i, 'couchbase'],
    [/horizon/i, 'horizon'],
    [/elm/i, 'elm'],
    [/datomic/i, 'datomic'],
    [/deployd/i, 'deployd'],
    [/hood\.?ie/i, 'hoodie'],
    [/kinvey/i, 'kinvey'],
    [/immutable/i, 'ImmutableJS'],
    [/kinto/i, 'kinto'],
    [/cerebral/i, 'cerebral'],
    [/mongo/i, 'MongoDB'],
    [/contentful/i, 'Contentful'],
    [/mysql/i, 'MySQL'],
    [/redis/i, 'Redis'],
    [/ember( |-|\.)?data/i, 'Ember Data'],
    [/rethink/i, 'RethinkDB'],
    [/^node$|node\.?js|node js/i, 'Node.js'],
    [/asp\. ?net|c#|\.net|dotnet/i, '.NET'],
    [/django/i, 'django'],
    [/rails|ruby on rails/i, 'Rails'],
    [/php/i, 'PHP'],
    [/restify/i, 'restify'],
    [/adonis/i, 'adonis'],
    [/python/i, 'python'],
    [/^go$|golang/i, 'golang'],
    [/java/i, 'java'],
    [/laravel/i, 'laravel'],
    [/elixir/i, 'elixir'],
    [/next\.?js/i, 'next.js'],
    [/scala/i, 'Scala'],
    [/couchdb/i, 'CouchDB'],
    [/trails/i, 'trails'],
    [/kraken/i, 'Kraken'],
    [/serverless/i, 'serverless'],
    [/graphql/i, 'GraphQL'],
    [/clojure/i, 'clojure'],
    [/socket\.?io/i, 'socket.io'],
    [/micro/i, 'micro'],
    [/firebase/i, 'firebase'],
    [/haskell/i, 'haskell'],
    [/qunit/i, 'Qunit'],
    [/karma/i, 'karma'],
    [/chai/i, 'chai'],
    [/protractor/i, 'protractor'],
    [/selenium/i, 'selenium'],
    [/nightwatch/i, 'nightwatch'],
    [/elm-test/i, 'elm-test'],
    [/tap/i, 'tap'],
    [/cucumber/i, 'cucumber'],
    [/sinon/i, 'sinon'],
    [/intern/i, 'intern'],
    [/ava/i, 'AVA'],
    [/lab/i, 'lab'],
    [/testcafe/i, 'testcafe'],
    [/junit/i, 'junit'],
    [/jest/i, 'jest'],
    [/cypress/i, 'cypress'],
    [/phantom/i, 'PhantomJS'],
    [/atomic/i, 'atomic design'],
    [/bem/i, 'BEM'],
    [/materialize/i, 'materialize'],
    [/post( |-|\.)?css/i, 'PostCSS'],
    [/bulma/i, 'Bulma'],
    [/semantic/i, 'semantic UI'],
    [/css( |\.|-)?modules/i, 'CSS modules'],
    [/tach\.+on/i, 'Tachyons'],
    [/material design/i, 'material design'],
    [/css\.?next/i, 'CSSnext'],
    [/pure\.?css/i, 'PureCSS'],
    [/skeleton/i, 'skeleton'],
    [/material\.?ui/i, 'Material UI'],
    [/styled\.?components/i, 'styled components'],
    [/bourbon/i, 'bourbon'],
    [/mill?igram/i, 'milligram'],
    [/uikit/i, 'uikit'],
    [/flexbox/i, 'flexbox'],
    [/topocoat/i, 'topocoat'],
    [/glamor/i, 'glamor'],
    [/radium/i, 'radium'],
    [/aphrodite/i, 'aphrodite'],
    [/styletron/i, 'styletron'],
    [/jss/i, 'JSS'],
    [/mdl/i, 'mdl'],
    [/vuetify/i, 'vuetify'],
    [/materiali(z|s)e/i, 'materialize'],
    [/yarn/i, 'yarn'],
    [/brunch/i, 'Brunch'],
    [/make/i, 'GNU Make'],
    [/broccoli|brocolli/i, 'Broccoli'],
    [/bower/i, 'Bower'],
    [/jspm/i, 'jspm'],
    [/fusebox/i, 'fusebox'],
    [/meteor/i, 'Meteor'],
    [/systemjs/i, 'SystemJS'],
    [/gradle/i, 'gradle'],
    [/stealjs/i, 'StealJS'],
    [/gulp/i, 'gulp'],
    [/babel/i, 'Babel'],
    [/weex/i, 'Weex'],
    [/xamarin/i, 'Xamarin'],
    [/pwa/i, 'PWA'],
    [/progressive web app/i, 'PWA'],
    [/nw\.js/i, 'nw.js'],
    [/nwjs/i, 'nw.js'],
    [/nw/i, 'nw.js'],
    [/expo/i, 'Expo'],
    [/Flutter/i, 'Flutter'],
    [/appcelerator/i, 'Appcelerator'],
    [/titanium/i, 'Appcelerator'],
    [/fuse/i, 'Fuse'],
    [/cef/i, 'CEF'],
    [/Chromium Embedded Framework/i, 'CEF'],
    [/Angular Native/i, 'Angular Native'],
    [/Elm native/i, 'Elm native'],
    [/Swift/i, 'Swift'],
    [/Kotlin/i, 'Kotlin'],
    [/yarn/i, 'yarn'],
    [/npm/i, 'npm'],
    [/nuget/i, 'Nuget'],
    [/composer/i, 'Composer'],
    [/elm/i, 'elm-package'],
    [/jspm/i, 'jspm'],
    [/pnpm/i, 'pnpm'],
    [/meteor/i, 'Meteor'],
    [/homebrew|brew/i, 'Homebrew'],
    [/leiningen/i, 'Leiningen'],
    [/maven/i, 'Maven'],
    [/immutable/i, 'ImmutableJS'],
    [/lodash/i, 'lodash'],
    [/jquery/i, 'jQuery'],
    [/Moment/i, 'moment'],
    [/rxjs/i, 'RxJS'],
    [/underscore/i, 'underscore'],
    [/ramda/i, 'Ramda'],
    [/axios/i, 'axios'],
    [/recompose/i, 'recompose'],
    [/^react$/i, 'React'],
    [/zepto/i, 'Zepto'],
    [/async/i, 'async'],
    [/atom/i, 'Atom'],
    [/webstorm/i, 'WebStorm'],
    [/phpstorm/i, 'PHPStorm'],
    [/intellij/i, 'IntelliJ'],
    [/sublime/i, 'Sublime Text'],
    [/vim/i, 'Vim'],
    [/emacs/i, 'Emacs'],
    [/brackets/i, 'Brackets'],
    [/Visual Studio/, 'Visual Studio'],
    [/notepad/i, 'Notepad++'],
    [/netbeans/i, 'Netbeans'],
    [/coda/i, 'Coda'],
    [/prettier/i, 'Prettier'],
    [/eslint/i, 'eslint'],
    [/tslint/i, 'tslint'],
    [/stylelint/i, 'Stylelint'],
    [/jshint/i, 'JSHint'],
    [/standardjs/i, 'StandardJS'],
    [/jscs/i, 'JSCS'],
    [/jslint/i, 'JSLint'],
    [/xo/i, 'XO'],
]